import { Injectable, inject } from '@angular/core';
import {
  HttpRequest,
  HttpHandler,
  HttpEvent,
  HttpInterceptor
} from '@angular/common/http';
import { Observable } from 'rxjs';
import { AuthService } from '../../login/auth.service';

@Injectable()
export class JwtInterceptor implements HttpInterceptor {

  #authService = inject(AuthService)

  constructor() {}
  language = localStorage.getItem('lang');

  intercept(request: HttpRequest<unknown>, next: HttpHandler): Observable<HttpEvent<unknown>> {
    let currentUser = this.#authService.currentUserValue
    // let expirationDate = new Date(currentUser.expiration);
        // if(expirationDate <= new Date()) {
        //   this.#authService.logout()
        // }
        request = request.clone({
          setHeaders: {
            Authorization : `Bearer ${currentUser?.token}`,
            // Authorization : `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlN1cGVyIEFkbWluIiwibmFtZWlkIjoiMGVhZWY4MWItMmUwNi00NDA0LTk0NTItMzdhYTM5MjI4ZDNmIiwiQnJhbmNoIjoiYmYyOGFlZjAtYmQ5ZC00YzAxLTk0YzItNjI3ZmEyMDA3Y2M1IiwiVHJlYXN1cnkiOiI0OTU1ZmQ5Yy0xZmZhLTRlNDktODNjNy1iYTlkNDBkMjZkNmYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiU3VwZXIgQWRtaW4iLCJQb3MuVmlldyIsIlBvcy5EaXNjb3VudCIsIk9yZGVycy5WaWV3IiwiQ2xpZW50LlZpZXciLCJDbGllbnQuQWRkIiwiQ2xpZW50LkVkaXQiLCJDbGllbnQuRGVsZXRlIiwiQ2F0ZWdvcmllcy5WaWV3IiwiQ2F0ZWdvcmllcy5BZGQiLCJDYXRlZ29yaWVzLkVkaXQiLCJDYXRlZ29yaWVzLkRlbGV0ZSIsIlN1YkNhdGVnb3JpZXMuVmlldyIsIlN1YkNhdGVnb3JpZXMuQWRkIiwiU3ViQ2F0ZWdvcmllcy5FZGl0IiwiU3ViQ2F0ZWdvcmllcy5EZWxldGUiLCJQcm9kdWN0cy5WaWV3IiwiUHJvZHVjdHMuQWRkIiwiUHJvZHVjdHMuRWRpdCIsIlByb2R1Y3RzLkRlbGV0ZSIsIkFycmFuZ2VzLlZpZXciLCJBcnJhbmdlcy5BZGQiLCJBcnJhbmdlcy5FZGl0IiwiQXJyYW5nZXMuRGVsZXRlIiwiQWRkaXRpb25zLlZpZXciLCJBZGRpdGlvbnMuQWRkIiwiQWRkaXRpb25zLkVkaXQiLCJBZGRpdGlvbnMuRGVsZXRlIiwiU2VydmljZXMuVmlldyIsIlNlcnZpY2VzLkFkZCIsIlNlcnZpY2VzLkVkaXQiLCJTZXJ2aWNlcy5EZWxldGUiLCJVc2Vycy5WaWV3IiwiVXNlcnMuQWRkIiwiVXNlcnMuRWRpdCIsIlVzZXJzLkRlbGV0ZSIsIlJvbGVzLlZpZXciLCJSb2xlcy5BZGQiLCJSb2xlcy5FZGl0IiwiUm9sZXMuRGVsZXRlIiwiQXJlYS5WaWV3IiwiQXJlYS5BZGQiLCJBcmVhLkVkaXQiLCJBcmVhLkRlbGV0ZSIsIlN0b3JhZ2VzLlZpZXciLCJTdG9yYWdlcy5BZGQiLCJTdG9yYWdlcy5FZGl0IiwiU3RvcmFnZXMuRGVsZXRlIiwiQnJhbmNoLlZpZXciLCJCcmFuY2guQWRkIiwiQnJhbmNoLkVkaXQiLCJCcmFuY2guRGVsZXRlIiwiQ29uZmlndXJhdGlvbi5WaWV3IiwiQ29uZmlndXJhdGlvbi5BZGRPclVwZGF0ZSIsIkNsaWVudFByb2ZpbGUuVmlldyIsIkNsaWVudFByb2ZpbGUuUGFpZCIsIkNsaWVudFByb2ZpbGUuUGFpZEFuZERlbGl2ZXJkIiwiQ2xpZW50UHJvZmlsZS5Db21taXNzaW9uIiwiQ2xpZW50UHJvZmlsZS5Nb250aGx5Q29taXNzaW9uIiwiQ2xpZW50UHJvZmlsZS5Qb3NpdGl2ZUJhbGFuY2UiLCJIb21lLlRvdGFsT3JkZXJzIiwiSG9tZS5Ub3RhbENhc2giLCJIb21lLlRvdGFsUmVtYWluaW5nIiwiSG9tZS5Ub3RhbERhbWFnZSIsIkhvbWUuT3JkZXJDcmVkaXQiLCJIb21lLkNsaWVudENyZWRpdCIsIkhvbWUuRGFpbHlSZXBvcnQiLCJJbnZvaWNlLlZpZXciLCJJbnZvaWNlLlBhaWQiLCJJbnZvaWNlLlBhaWRBbmREZWxpdmVyZCIsIkludm9pY2UuRGVsZXRlIiwiSW52b2ljZS5SZWFkeUZvckRlbGV0ZSIsIkludm9pY2UuUHJpbnQiLCJJbnZvaWNlLlByaW50VGFncyIsIkludm9pY2UuQWRkV29ya2VycyIsIkludm9pY2UuQ2hhbmdlU3RvcmFnZUxvY2F0aW9uIiwiSW52b2ljZS5Db21wbGV0ZUl0ZW1zIiwiSW52b2ljZS5Db21wbGV0ZU9yZGVyIiwiSW52b2ljZS5EZWxpdmVySXRlbXMiLCJJbnZvaWNlLkRlbGl2ZXJPcmRlciIsIkludm9pY2UuQ3VzdG9tSXRlbVF1YW50aXR5IiwiSW52b2ljZS5JdGVtU3RvcmFnZUxvY2F0aW9uIiwiSW52b2ljZS5BZGROb3RlcyIsIkludm9pY2UuRGlzY291bnQiLCJSZXBvcnRzLlZpZXciLCJSZXBvcnRzLk9yZGVyUmVwb3J0IiwiUmVwb3J0cy5PcmRlclJlcG9ydERhbWFnZSIsIlJlcG9ydHMuVmlld0FsbE9yZGVycyIsIlJlcG9ydHMuUmVhZHlGb3JEZWxldGUiLCJSZXBvcnRzLk9yZGVyUmVwb3J0QnJhbmNoZXMiLCJSZXBvcnRzLlRyZWFzdXJ5UmVwb3J0IiwiUmVwb3J0cy5BbGxUcmVhc3VyeVJlcG9ydCIsIlJlcG9ydHMuQ3VycmVudEJyYW5jaFRyZWFzdXJ5UmVwb3J0IiwiUmVwb3J0cy5Vc2VyRGlzY291bnRzIl0sImV4cCI6MTY5MjUyNTM1NH0.KZcj3GuPH3A0SQmqWPxAskXB5rN-1HmCH1w_wZfi9JU`,
            'Accept-language': this.language == 'ar' ? 'ar' : 'en'
          }
        })
    return next.handle(request);
  }
}
